package net.theevilreaper.stelaris.cli.generator.dart.util

import net.theevilreaper.dartpoet.DartFileBuilder
import net.theevilreaper.dartpoet.directive.Directive
import net.theevilreaper.dartpoet.directive.DirectiveFactory
import net.theevilreaper.dartpoet.directive.DirectiveType
import java.nio.file.Files
import java.nio.file.Path

/**
 * The header every generated file starts with.
 * The first line follows the convention of the Dart tooling (e.g. `build_runner`), so editors and
 * analyzers recognize the file as generated.
 */
const val GENERATED_FILE_HEADER: String =
    "// GENERATED CODE - DO NOT MODIFY BY HAND\n" +
        "// Generated by the Stelaris CLI: https://github.com/OneLiteFeatherNET/Stelaris-CLI"

private const val DART_FILE_ENDING = ".dart"

/**
 * The folder of the handwritten api (`lib/src/api`), which is a sibling of the generation folder (`lib/src/generated`).
 */
private const val API_FOLDER = "api"

/**
 * Creates the import of a file from the handwritten api of the package.
 * A file which uses this import has to be written with the parent of the generation folder as base directory.
 * @param fileName the name of the api file, e.g. `rgb_color.dart`
 * @param folderDepth the number of folders between the generation folder and the file, e.g. 2 for `entity/variant`
 * @return the created [Directive]
 */
fun apiImport(fileName: String, folderDepth: Int = 1): Directive {
    require(folderDepth > 0) { "The folder depth must be positive" }
    return DirectiveFactory.create(DirectiveType.RELATIVE, "${"../".repeat(folderDepth + 1)}$API_FOLDER/$fileName")
}

/**
 * Builds and writes the file to the given [folder] and marks it as generated.
 * Every generator should use this method instead of writing a [net.theevilreaper.dartpoet.DartFile] directly,
 * so all files share the same header and end with a newline.
 * @param folder the folder where the file should be written
 * @param baseDir the directory relative imports must stay within; defaults to [folder]
 * @return the [Path] of the written file
 */
fun DartFileBuilder.writeGenerated(folder: Path, baseDir: Path = folder): Path {
    build().write(folder, baseDir)
    val fileName = if (name.endsWith(DART_FILE_ENDING)) name else "$name$DART_FILE_ENDING"
    val filePath = folder.resolve(fileName)
    val content = Files.readString(filePath).trimEnd()
    Files.writeString(filePath, "$GENERATED_FILE_HEADER\n\n$content\n")
    return filePath
}
