blank_issues_enabled: false
contact_links:
  - name: OneLiteFeather Discord
    url: https://discord.onelitefeather.net/
    about: Please join our Discord server if you have any questions or concerns.
    icon: https://github.com/simple-icons/simple-icons/blob/develop/icons/discord.svg