name: Generate and Upload Dart Project

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    env:
      ONELITEFEATHER_MAVEN_USERNAME: ${{ secrets.ONELITEFEATHER_MAVEN_USERNAME }}
      ONELITEFEATHER_MAVEN_PASSWORD: ${{ secrets.ONELITEFEATHER_MAVEN_PASSWORD }}
    steps:
      - name: Checkout stelaris-cli repository
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Extract and parse version from tag
        id: parse_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"

          echo "TAG_NAME=$TAG" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Build JAR gradle project
        run: ./gradlew clean build

      - name: Run Stelaris CLI
        env:
          stelaris.cli.username: 'stelaris-bot'
          stelaris.cli.password: ${{ secrets.DART_REPO_TOKEN }}
          stelaris.cli.cloneUrl: https://github.com/${{ secrets.TARGET_REPOSITORY }}.git
        run: java -jar build/libs/stelaris-cli.jar -version ${{ env.VERSION }} -type git -experimental
      
